// Copyright (c) Open Enclave SDK contributors.
// Licensed under the MIT License.

#include <cmath>
#include <cstdio>

// Include the trusted helloworld header that is generated
// during the build. This file is generated by calling the
// sdk tool oeedger8r against the helloworld.edl file.
#include "../build/enclave/helloworld_t.h"
#include "openenclave/bits/result.h"

using namespace std;

// This is the function that the host calls.
void enclave_helloworld()
{
    fprintf(stdout, "[ENCLAVE] Hello world from the enclave\n");

    // Callback into the host
    oe_result_t result = host_helloworld();
    if (result != OE_OK)
    {
      fprintf(stderr, "[ENCLAVE] Call to host_helloworld failed: result=%d (%s)\n", result, oe_result_str(result));
    }
}
