// Copyright (c) Open Enclave SDK contributors.
// Licensed under the MIT License.

#include <cmath>
#include <cstdint>
#include <cstdio>
#include <cstring>

// Include the trusted helloworld header that is generated
// during the build. This file is generated by calling the
// sdk tool oeedger8r against the helloworld.edl file.
#include "../build/enclave/calu_t.h"
#include "openenclave/bits/defs.h"
#include "openenclave/bits/result.h"
#include "openenclave/log.h"
#include <openenclave/tracee.h>

using namespace std;

void enclave_customized_log(
    void* context,
    oe_log_level_t level,
    uint64_t thread_id,
    const char* message)
{
    char modified_log[200];

    sprintf(
        modified_log,
        "E, %s, %lx, %s",
        oe_log_level_strings[level],
        thread_id,
        message);

    /*
     * Add logic here to modify the log message, to obscure enclave logs from
     * the host. The context might be used, for example, to transfer a
     * shared/public/private secret, that may be used to encrypt the log
     * message.
     *
     * NOTE: Do not use operations based on OE's host filesystem support
     * in this function, they do not work consistently. If used, the
     * logs generated after oe_terminate_enclave() cause the program to crash
     * with a segmentation fault (issue #4349).
     */
    OE_UNUSED(context);

    /* invoke ocall to copy enclave logs to file */
    oe_result_t result = host_transfer_logs_to_file(modified_log, strlen(modified_log));

    OE_UNUSED(result);
}

void enclave_set_log_callback()
{
  // make sure that logs use the enclave_customized_log function
  oe_enclave_log_set_callback(NULL, enclave_customized_log);
}

// This is the function that the host calls.
void enclave_helloworld()
{
    fprintf(stdout, "[ENCLAVE] Hello world from the enclave\n");

    // Callback into the host
    oe_result_t result = host_helloworld();
    if (result != OE_OK)
    {
      fprintf(stderr, "[ENCLAVE] Call to host_helloworld failed: result=%d (%s)\n", result, oe_result_str(result));
    }
}
